namespace Canducci.Recurrence
{
    public class BillingAddress : Address { }
}
//"banking_billet"
//    "customer"
//        "name"
//        "cpf"
//        "email"
//        "phone_number"
//        "birth"
//        "address"
//            "street"
//            "number"
//            "neighborhood"
//            "zipcode"
//            "city"
//            "complement"
//            "state"
//        "juridical_person"
//            "corporate_name"
//            "cnpj"
//    "expire_at"
//    "discount"
//        "type"
//            "percentage"
//            "currency"
//        "value"
//    "conditional_discount"
//        "type"
//            "percentage",
//            "currency"
//        "value"
//        "until_date"
//    "configurations"
//        "fine"
//        "interest"
//    "message"
